[package]
name = "rust-mmr-sample"
version = "0.1.0"
authors = ["mathiastj <2278040+mathiastj@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.13.0"